/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FractPack;

import java.awt.Color;
import javax.swing.WindowConstants;

/**
 *
 * @author Marina Nik
 */
public class StarFractEditGUI extends javax.swing.JFrame {

    /**
     * Creates new form StarFractEditGUI
     */
    public StarFractEditGUI() {
        initComponents();
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LenLabel = new javax.swing.JLabel();
        LenTextField = new javax.swing.JTextField();
        NumLabel = new javax.swing.JLabel();
        NumTextField = new javax.swing.JTextField();
        ShrinkLabel = new javax.swing.JLabel();
        ShrinkTextField = new javax.swing.JTextField();
        ColorLabel = new javax.swing.JLabel();
        ColorChoose = new javax.swing.JColorChooser();
        ConfirmButton = new javax.swing.JToggleButton();
        CancelButton = new javax.swing.JButton();
        StrokeLabel = new javax.swing.JLabel();
        StrokeTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LenLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        LenLabel.setText("Init Length");

        LenTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        NumLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        NumLabel.setText("Number of lines");

        NumTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        ShrinkLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ShrinkLabel.setText("Line Shrinking coef");

        ShrinkTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        ColorLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ColorLabel.setText("Line Color");

        ConfirmButton.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ConfirmButton.setText("Confirm");
        ConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmButtonActionPerformed(evt);
            }
        });

        CancelButton.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        StrokeLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        StrokeLabel.setText("Line Thickness");

        StrokeTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ColorChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ColorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LenTextField)
                                    .addComponent(LenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NumTextField))))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ShrinkLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ShrinkTextField))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(StrokeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(StrokeTextField))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ConfirmButton, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(CancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(StrokeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShrinkLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConfirmButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LenTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(NumTextField)
                    .addComponent(ShrinkTextField)
                    .addComponent(StrokeTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(ColorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ColorChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmButtonActionPerformed
        // TODO add your handling code here:
        if (!LenTextField.getText().isBlank()){
            if (Double.parseDouble(LenTextField.getText()) == 0)
                GUI.starFractLineLen = 200.0;  //default
            else
                GUI.starFractLineLen = Double.parseDouble(LenTextField.getText());
        }
        if (!NumTextField.getText().isBlank()){
            if (Integer.parseInt(NumTextField.getText()) == 0)
                GUI.starFractLineNum = 7;  //default
            else
                GUI.starFractLineNum = Integer.parseInt(NumTextField.getText());
        }
        if (!ShrinkTextField.getText().isBlank()){
            if (Double.parseDouble(ShrinkTextField.getText()) == 0)
                GUI.starFractLineShrink = 2.5;  //default
            else
                GUI.starFractLineShrink = Double.parseDouble(ShrinkTextField.getText());
        }
        if (!StrokeTextField.getText().isBlank()){
            if (Double.parseDouble(StrokeTextField.getText()) == 0)
                GUI.starFractLineStroke = 1.0;  //default
            else
                GUI.starFractLineStroke = Double.parseDouble(StrokeTextField.getText());
        }
        if (ColorChoose.getColor().getRGB() != GUI.colorNow.getRGB())
            GUI.colorNow = ColorChoose.getColor();
//        if (GUI.DrawingPanel.getBackground().getRGB() == ColorChoose.getColor().getRGB())
//            GUI.colorNow = Color.BLACK;
        dispose();
    }//GEN-LAST:event_ConfirmButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StarFractEditGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StarFractEditGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StarFractEditGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StarFractEditGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StarFractEditGUI().setVisible(true);
                LenTextField.setText(Double.toString(GUI.starFractLineLen));
                NumTextField.setText(Integer.toString(GUI.starFractLineNum));
                ShrinkTextField.setText(Double.toString(GUI.starFractLineShrink));
                StrokeTextField.setText(Double.toString(GUI.starFractLineStroke));
                ColorChoose.setColor(GUI.colorNow);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private static javax.swing.JColorChooser ColorChoose;
    private javax.swing.JLabel ColorLabel;
    private javax.swing.JToggleButton ConfirmButton;
    private javax.swing.JLabel LenLabel;
    private static javax.swing.JTextField LenTextField;
    private javax.swing.JLabel NumLabel;
    private static javax.swing.JTextField NumTextField;
    private javax.swing.JLabel ShrinkLabel;
    private static javax.swing.JTextField ShrinkTextField;
    private javax.swing.JLabel StrokeLabel;
    private static javax.swing.JTextField StrokeTextField;
    // End of variables declaration//GEN-END:variables
}
