/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FractPack;

import java.awt.Color;
import javax.swing.WindowConstants;

/**
 *
 * @author Marina Nik
 */
public class TreeFractEditGUI extends javax.swing.JFrame {

    /**
     * Creates new form TreeFractEditGUI
     */
    public TreeFractEditGUI() {
        initComponents();
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LenLabel = new javax.swing.JLabel();
        LenTextField = new javax.swing.JTextField();
        AngleLeftLabel = new javax.swing.JLabel();
        AngleLeftTextField = new javax.swing.JTextField();
        AngleRightLabel = new javax.swing.JLabel();
        AngleRightTextField = new javax.swing.JTextField();
        ShrinkLabel = new javax.swing.JLabel();
        ShrinkTextField = new javax.swing.JTextField();
        StrokeLabel = new javax.swing.JLabel();
        StrokeTextField = new javax.swing.JTextField();
        ColorLabel = new javax.swing.JLabel();
        ColorChoose = new javax.swing.JColorChooser();
        ConfirmButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        InitAngleLabel = new javax.swing.JLabel();
        InitAngleTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LenLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        LenLabel.setText("Init Length");

        LenTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        AngleLeftLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        AngleLeftLabel.setText("Angle to Left");

        AngleLeftTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        AngleRightLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        AngleRightLabel.setText("Angle to Right");

        AngleRightTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        ShrinkLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ShrinkLabel.setText("Line Shrink coef");

        ShrinkTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        StrokeLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        StrokeLabel.setText("Line Stroke");

        StrokeTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        ColorLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ColorLabel.setText("Line Color");

        ConfirmButton.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ConfirmButton.setText("Confirm");
        ConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmButtonActionPerformed(evt);
            }
        });

        CancelButton.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        InitAngleLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        InitAngleLabel.setText("Init Angle");

        InitAngleTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ColorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LenTextField)
                            .addComponent(LenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AngleLeftLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(AngleLeftTextField))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AngleRightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(AngleRightTextField))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ShrinkLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ShrinkTextField))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(StrokeTextField)
                            .addComponent(StrokeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InitAngleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(InitAngleTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ColorChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(InitAngleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ShrinkLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(AngleRightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AngleLeftLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addComponent(StrokeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(InitAngleTextField)
                            .addComponent(LenTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(AngleLeftTextField)
                            .addComponent(AngleRightTextField)
                            .addComponent(ShrinkTextField)
                            .addComponent(StrokeTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ColorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(ColorChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmButtonActionPerformed
        // TODO add your handling code here:
        if (!LenTextField.getText().isBlank()){
            if (Double.parseDouble(LenTextField.getText()) == 0)
                GUI.treeFractLineLen = 200.0;  //default
            else
                GUI.treeFractLineLen = Double.parseDouble(LenTextField.getText());
        }
        if (!AngleLeftTextField.getText().isBlank()){
            if (Double.parseDouble(AngleLeftTextField.getText()) == 0)
                GUI.treeFractAngleLeft = - 30;  //default
            else
                GUI.treeFractAngleLeft = Double.parseDouble(AngleLeftTextField.getText());
        }
        if (!AngleRightTextField.getText().isBlank()){
            if (Double.parseDouble(AngleRightTextField.getText()) == 0)
                GUI.treeFractAngleRight = 30;  //default
            else
                GUI.treeFractAngleRight = Double.parseDouble(AngleRightTextField.getText());
        }
        if (!ShrinkTextField.getText().isBlank()){
            if (Double.parseDouble(ShrinkTextField.getText()) == 0)
                GUI.treeFractLineShrink = 0.75;  //default
            else
                GUI.treeFractLineShrink = Double.parseDouble(ShrinkTextField.getText());
        }
        if (!StrokeTextField.getText().isBlank()){
            if (Double.parseDouble(StrokeTextField.getText()) == 0)
                GUI.treeFractLineStroke = 30.0;  //default
            else
                GUI.treeFractLineStroke = Double.parseDouble(StrokeTextField.getText());
        }
        if (!InitAngleTextField.getText().isBlank()){
                GUI.treeFractInitAngle = Double.parseDouble(InitAngleTextField.getText());
        }
        if (ColorChoose.getColor().getRGB() != GUI.colorNow.getRGB())
            GUI.colorNow = ColorChoose.getColor();
        dispose();
    }//GEN-LAST:event_ConfirmButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TreeFractEditGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TreeFractEditGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TreeFractEditGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TreeFractEditGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TreeFractEditGUI().setVisible(true);
                AngleLeftTextField.setText(Double.toString(GUI.treeFractAngleLeft));
                AngleRightTextField.setText(Double.toString(GUI.treeFractAngleRight));
                LenTextField.setText(Double.toString(GUI.treeFractLineLen));
                ShrinkTextField.setText(Double.toString(GUI.treeFractLineShrink));
                StrokeTextField.setText(Double.toString(GUI.treeFractLineStroke));
                InitAngleTextField.setText(Double.toString(GUI.treeFractInitAngle));
                ColorChoose.setColor(GUI.colorNow);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AngleLeftLabel;
    private static javax.swing.JTextField AngleLeftTextField;
    private javax.swing.JLabel AngleRightLabel;
    private static javax.swing.JTextField AngleRightTextField;
    private javax.swing.JButton CancelButton;
    private static javax.swing.JColorChooser ColorChoose;
    private javax.swing.JLabel ColorLabel;
    private javax.swing.JButton ConfirmButton;
    private javax.swing.JLabel InitAngleLabel;
    private static javax.swing.JTextField InitAngleTextField;
    private javax.swing.JLabel LenLabel;
    private static javax.swing.JTextField LenTextField;
    private javax.swing.JLabel ShrinkLabel;
    private static javax.swing.JTextField ShrinkTextField;
    private javax.swing.JLabel StrokeLabel;
    private static javax.swing.JTextField StrokeTextField;
    // End of variables declaration//GEN-END:variables
}
