/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FractPack;

import java.awt.Color;
import javax.swing.WindowConstants;

/**
 *
 * @author Marina Nik
 */
public class TriangleFractEditGUI extends javax.swing.JFrame {

    /**
     * Creates new form ShapeFractEditGUI
     */
    public TriangleFractEditGUI() {
        initComponents();
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InitLenLabel = new javax.swing.JLabel();
        InitLenTextField = new javax.swing.JTextField();
        ColorLabel = new javax.swing.JLabel();
        ColorChoose = new javax.swing.JColorChooser();
        StrokeLabel = new javax.swing.JLabel();
        StrokeTextField = new javax.swing.JTextField();
        ThinLabel = new javax.swing.JLabel();
        LineThinTextField = new javax.swing.JTextField();
        ConfirmButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        FillCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InitLenLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        InitLenLabel.setText("Init Length");

        InitLenTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        ColorLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ColorLabel.setText("Color");

        StrokeLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        StrokeLabel.setText("Line stroke");

        StrokeTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        ThinLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ThinLabel.setText("Line thin. coef");

        LineThinTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        ConfirmButton.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ConfirmButton.setText("Confirm");
        ConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmButtonActionPerformed(evt);
            }
        });

        CancelButton.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        FillCheckBox.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        FillCheckBox.setText("Fill fractal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ColorChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ColorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InitLenTextField)
                            .addComponent(InitLenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(StrokeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LineThinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(StrokeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ThinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(FillCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(InitLenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StrokeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ThinLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FillCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(InitLenTextField)
                    .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StrokeTextField)
                    .addComponent(LineThinTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ColorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ColorChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void ConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmButtonActionPerformed
        // TODO add your handling code here:
        if (!InitLenTextField.getText().isBlank()){
            if (Double.parseDouble(InitLenTextField.getText()) == 0)
                GUI.shapeFractLineLen = 750.0;  //default
            else
                GUI.shapeFractLineLen = Double.parseDouble(InitLenTextField.getText());
        }
        if (!LineThinTextField.getText().isBlank()){
            if (Double.parseDouble(LineThinTextField.getText()) == 0)
                GUI.shapeFractLineThin = 1.0;  //default
            else
                GUI.shapeFractLineThin = Double.parseDouble(LineThinTextField.getText());
        }
        if (!StrokeTextField.getText().isBlank()){
            if (Double.parseDouble(StrokeTextField.getText()) == 0)
                GUI.shapeFractLineStroke = 1.0;  //default
            else
                GUI.shapeFractLineStroke = Double.parseDouble(StrokeTextField.getText());
        }
        if (FillCheckBox.isSelected())
            GUI.shapeFractFill = true;
        if (!FillCheckBox.isSelected())
            GUI.shapeFractFill = false;
        if (ColorChoose.getColor().getRGB() != GUI.colorNow.getRGB())
            GUI.colorNow = ColorChoose.getColor();
        dispose();
    }//GEN-LAST:event_ConfirmButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TriangleFractEditGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TriangleFractEditGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TriangleFractEditGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TriangleFractEditGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
               //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TriangleFractEditGUI().setVisible(true);
                InitLenTextField.setText(Double.toString(GUI.shapeFractLineLen));
                LineThinTextField.setText(Double.toString(GUI.shapeFractLineThin));
                StrokeTextField.setText(Double.toString(GUI.shapeFractLineStroke));
                if (GUI.shapeFractFill)
                    FillCheckBox.setSelected(true);
                else
                    FillCheckBox.setSelected(false);
                ColorChoose.setColor(GUI.colorNow);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private static javax.swing.JColorChooser ColorChoose;
    private javax.swing.JLabel ColorLabel;
    private javax.swing.JButton ConfirmButton;
    private static javax.swing.JCheckBox FillCheckBox;
    private javax.swing.JLabel InitLenLabel;
    private static javax.swing.JTextField InitLenTextField;
    private static javax.swing.JTextField LineThinTextField;
    private javax.swing.JLabel StrokeLabel;
    private static javax.swing.JTextField StrokeTextField;
    private javax.swing.JLabel ThinLabel;
    // End of variables declaration//GEN-END:variables
}
